#!/usr/bin/bash
texlua addhandi.lua "$1" "$2"
cp handiscn.htm ~/server-zaloha/web-new/src/
cp handiscn_b.htm ~/server-zaloha/web-new/src/
# scp index.html knihovna-new:/home/hoftich/nginx/handi/index.html
cp index.html ../pedf-web-navrh/backup/handi/

